/// <reference lib="webworker" />
/// <reference types="vite-plugin-pwa/client" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope & typeof globalThis;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Install event
self.addEventListener('install', (event) => {
  console.log('[Service Worker] Installing...');
  self.skipWaiting();
});

// Activate event
self.addEventListener('activate', (event) => {
  console.log('[Service Worker] Activating...');
  event.waitUntil(self.clients.claim());
});

// Push event - handle incoming push notifications
self.addEventListener('push', (event) => {
  console.log('[SW] 🔔 Push notification received!');
  console.log('[SW] Event data exists:', !!event.data);
  
  if (!event.data) {
    console.warn('[SW] ⚠️ Push event has no data - showing default notification');
    event.waitUntil(
      self.registration.showNotification('Zubix', {
        body: 'You have a new notification',
        icon: '/pwa-192x192.png',
        badge: '/zubixfavicon.png',
        tag: 'zubix-default',
        requireInteraction: false
      })
    );
    return;
  }

  let notificationData: any;
  try {
    const rawText = event.data.text();
    console.log('[SW] 📦 Raw push data:', rawText);
    notificationData = JSON.parse(rawText);
    console.log('[SW] ✅ Parsed notification data:', notificationData);
  } catch (error) {
    console.error('[SW] ❌ Failed to parse push data:', error);
    notificationData = {
      title: 'Zubix',
      body: event.data.text() || 'You have a new notification',
    };
  }

  const {
    title = 'Zubix',
    body = 'You have a new notification',
    icon = '/pwa-192x192.png',
    badge = '/zubixfavicon.png',
    data = {},
  } = notificationData;

  console.log('[SW] 📢 Showing notification:', { title, body });

  const options: NotificationOptions = {
    body,
    icon,
    badge,
    data: {
      ...data,
      dateTime: Date.now(),
    },
    vibrate: [200, 100, 200],
    tag: data.notificationId || `zubix-${Date.now()}`,
    requireInteraction: true, // Changed to true for better visibility
    renotify: true,
    silent: false
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
      .then(() => {
        console.log('[SW] ✅ Notification displayed successfully!');
      })
      .catch((error) => {
        console.error('[SW] ❌ Failed to show notification:', error);
      })
  );
});

// Notification click event
self.addEventListener('notificationclick', (event) => {
  console.log('[Service Worker] Notification clicked:', event);
  
  event.notification.close();

  if (event.action === 'close') {
    return;
  }

  // Get the URL to open
  const urlToOpen = event.notification.data?.url || '/notifications';
  const origin = self.location.origin;
  const fullUrl = new URL(urlToOpen, origin).href;

  event.waitUntil(
    self.clients.matchAll({
      type: 'window',
      includeUncontrolled: true,
    }).then((clientList) => {
      // Check if there's already a window open
      for (const client of clientList) {
        if (client.url === fullUrl && 'focus' in client) {
          return client.focus();
        }
      }
      
      // If no window is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(fullUrl);
      }
    })
  );
});

// Handle push subscription changes
self.addEventListener('pushsubscriptionchange', (event: any) => {
  console.log('[Service Worker] Push subscription changed');
  
  event.waitUntil(
    self.registration.pushManager
      .subscribe(event.oldSubscription?.options || {
        userVisibleOnly: true
      })
      .then((subscription) => {
        console.log('[Service Worker] Resubscribed:', subscription);
      })
      .catch((error) => {
        console.error('[Service Worker] Resubscription failed:', error);
      })
  );
});
